오픈마켓 [STEP2] Brendan
yagom-academy/ios-open-market-new pull request #12
Opened 2022-02-03 03:11 UTC by gjwlsdnr0115

@zdodev  
안녕하세요 STEP2 PR 리뷰 부탁드리겠습니다!\
 STEP2 주요 사항은 두가지 입니다.
 - `UICollectionViewFlowLayout`을 이용하여 List 형태와 Grid 형태를 구현하기
 - `Storyboard`를 사용하지 않고 코드로만 UI를 구현하기

 # UICollectionViewFlowLayout
 - List와 Grid 형태의 `CollectionView`를 모두 구현하기 위해 하나의 `CollectionView `에 두가지 `FlowLayout`을 설정했습니다.
 - `SegmentedControl`의 값이 변하게 되면 그에 따라 해당되는 레이아웃으로 바뀝니다.
 - 또한 각각의 형태에 맞는 셀을 두가지 만들었고, `cellForRowAt` 메서드에서 `switch`문을 통해 적절한 셀을 가져와 사용하도록 했습니다.
 - 추가적으로 List와 Grid 형태를 오고갈때 애니메이션을 적용했습니다.

# 궁금한점
- 앱을 시뮬레이터에서 실행할 때, List와 Grid 레이아웃을 바꾸게 되면 콘솔에 AutoLayoutConstraint가 conflict가 일어나고 있다는 로그가 뜹니다.
- 하나의 셀의 레이아웃을 바꾸는게 아니라 List셀 Grid셀 두개를 완전히 바꿔가면서 사용하는데 레이아웃 충돌이 일어나는 이유를 파악하기 어려운것 같습니다.
- 일단은 앱이 동작하고 외관상 보여지는 부분에서는 큰 문제는 없어보이지만 찝찝한 부분이 있는 상황입니다.

2022-02-04 13:05 UTC, zdodev requested changes
안녕하세요. @gjwlsdnr0115 !
스텝2 PR 축하합니다.🎉

전반적으로 깔끔하게 구현 잘해주셨습니다.
다만 현재 상품 데이터가 보이지 않는 에러가 발생하고 있습니다.
`Unable to decode data.` 문구가 출력되는데 해당 부분 확인 부탁드립니다!
화면이 정상적으로 출력되면 더 자세하게 보도록 하겠습니다!

몇 가지 질문과 생각을 좀 남겨보았습니다. 같이 의견 나눠보면 좋을 것 같습니다.🤗

2022-02-04 13:05 UTC, zdodev commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        loadingIndicatorView.startAnimating()
로딩 간 indicator 애니메이션 동작을 구현해보셨네요. 좋습니다.👍

2022-02-04 13:05 UTC, zdodev commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
`selectedSegmentIndex`가 0일 때는 리스트, 1일 때는 그리드 형태로 전환되도록 구현해보셨네요!
그리고 `isListView` 프로퍼티의 타입이 `Bool` 타입으로 리스트 뷰인지 아닌지에 대한 의미가 전달되지만
해당 프로퍼티가 `false` 일 경우 그리드 뷰로 전환되어야 한다는 의미를 가지기는 어렵지 않나 생각이 들었습니다.😁
`true`, `false`로 리스트 뷰와 그리드 뷰를 나타내기 보다는 보다 명확하게 뷰를 나타낼 수 있는 표현 방법을 적용해보는 것은 어떨까요?
설정할 수 있는 뷰가 리스트, 그리드 외에도 더 늘어날 경우, 유연하게 대처해 볼 수 있을 것 같기도 합니다!
지금도 좋아요! 지금 방식으로 진행하셔도 무방합니다! 의견이 있다면 말씀해주세요.😁

2022-02-04 13:05 UTC, zdodev commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        return 0
다음 표현법은 어때요?🙃
```swift
productListData?.pages.count ?? 0
```

2022-02-04 13:05 UTC, zdodev commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.rootViewController = navigationController
`pushViewController` 메서드를 사용하여 첫 화면을 구성해보셨네요!
`rootViewController`를 설정하는 대신 push 방식을 사용하신 이유가 궁금합니다.🤔

2022-02-04 13:05 UTC, zdodev commented on OpenMarket/OpenMarket/View/ProductListCollectionViewCell.swift
> +    func bind(item data: ProductData) {
셀 데이터를 설정하는 메서드를 구현해보셨네요. 좋습니다.👍

2022-02-04 13:05 UTC, zdodev commented on OpenMarket/OpenMarket/Extension/UIImageView+Extension.swift
> +    }
`UIImageView` 에 비동기로 그림 데이터를 가져오도록 익스텐션을 구현해보셨네요. 좋습니다.👍

2022-02-04 13:05 UTC, zdodev commented on OpenMarket/OpenMarket/Model/ProductData.swift
> +import UIKit
`UIKit`을 사용하지 않고 있다면 제거하셔도 좋습니다!

2022-02-06 06:05 UTC, gjwlsdnr0115 commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        }
말씀해주신 부분 고민해 보고 `LayoutType`라는 `enum`을 사용하는 방법을 적용 해봤습니다. 프로퍼티의 의미가 좀더 쉽게 다가오는 것 같습니다! `cellForRowAt` 메서드에서도 `switch`문을 이용해서 적절한 셀을 사용하도록 했습니다.

2022-02-06 06:06 UTC, gjwlsdnr0115 commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +        return 0
훨씬 깔끔한 표현법인것 같네요! 감사합니다~~

2022-02-06 06:07 UTC, gjwlsdnr0115 commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        window?.rootViewController = navigationController
처음에는 `navigationController`의 `rootViewController` 프로퍼티에 접근할 수 없어서 `pushViewController`를 사용했는데 찾아보니 생성자에서 파라미터로 전달하면 되더라고요! 그래서 이 부분은 수정했습니다!

2022-02-06 06:10 UTC, gjwlsdnr0115 commented
말씀해주신 부분 수정해서 커밋했습니다. `Unable to decode data.` 에러 관련해서는 기존에 `price` 값을 `Int`로 디코딩 하도록 구현했는데 실제 데이터는 `Double` 타입으로 와서 발생한 것 같습니다. 이부분 관련하여 수정하니 문제 없이 동작했습니다. 감사합니다~

2022-02-07 09:53 UTC, zdodev approved these changes
안녕하세요. @gjwlsdnr0115 !

스텝2 피드백 반영 잘해주셨습니다!
디코딩 문제도 잘 해결되었고, 리스트, 그리드 레이아웃도 잘 표현됩니다.😁

그리고 처음에 질문주셨던 것 처럼 그리드 변경 시 오토레이아웃 충돌 에러를 볼 수 있었습니다.
혹시 다음 Xcode 의 `Layout Issues`를 확인해 볼 수 있을까요?😲 오토레이아웃 설정에 대해서
다양한 힌트를 얻을 수 있을 수 있을 것 같아요!
<img width="523" alt="1" src="https://user-images.githubusercontent.com/67548251/152764767-85d4651d-dd08-4414-8b10-304b0adaecdc.png">

이 부분은 다음 스텝 진행과 함께 수정해봐도 좋을 것 같아요~ 같이 의견을 나눠봐도 좋겠습니다!
스텝2는 여기서 마무리 하도록 하겠습니다. 고생하셨습니다.🤗

2022-02-07 09:53 UTC, zdodev commented on OpenMarket/OpenMarket/Controller/ProductListViewController.swift
> +    private enum LayoutType {
`private`으로 선언 좋습니다.👍
리스트와 그리드를 사용하는 코드를 한결 쉽게 볼 수 있었습니다.😁

2022-02-07 09:53 UTC, zdodev commented on OpenMarket/OpenMarket/SceneDelegate.swift
> +        let navigationController: UINavigationController = UINavigationController(rootViewController: ProductListViewController())
👍

2022-02-07 09:53 UTC, merged