오픈마켓 [STEP2] liam
yagom-academy/ios-open-market-new pull request #13
Opened 2022-02-03 05:45 UTC by liam-777

@zdodev

소대 안녕하세요 ~ 항상 꼼꼼한 리뷰 감사합니다!
STEP2 리뷰 부탁드립니다 !!

# 구현 내용 및 고민한 점

* cell size
  * 하나의 컬렉션뷰에 list 화면용 cell, grid 화면용 cell 두 가지를 구현하여 segmentedControl 값에 따라 적용하였습니다.
  * UICollectionViewDelegateFlowLayout을 채택하여서 각 셀의 필요한 크기를 sizeForItemAt에서 반환하도록 하였습니다.
  *  구현 초기에는 오토레이아웃에 따른 self sizing cell을 구현하고자 했는데, 가로 모드 대응 문제도 있었고 매번 레이아웃을 재계산하는 방법보다 성능상으로 이점을 가질 수 있을 것 같아서 sizeForItemAt에서 고정 크기를 반환하는 방법으로 수정하였습니다.

* 데이터 fetching
  * 무한 스크롤링 구현 
    *  초기 50개의 데이터를 로드해놓고 화면에 보여주도록 하였습니다.
    *  willDisplay에서는 마지막 cell 이전 10번째가 되면 다음 데이터를 fetch 하도록 구현하였습니다.
    * 만약 willDisplay에서 데이터 fetch에 시간이 오래 걸려 데이터를 불러오지 못했다면 footer view를 통해 activityIndicator를 보여주도록 하였습니다.
    * cellforItem에서 이미지 로드를 비동기처리할 수 있도록 ImageLoader에 loadImage 타입 메서드를 구현하였습니다.

2022-02-04 14:41 UTC, zdodev requested changes
안녕하세요. @liam-777 !
스텝2 PR 축하합니다.🎉

전체적으로 읽기 수월했던 것 같습니다!
오토레이아웃 구현과 셀 구성, 이미지 처리도 잘 구현되었습니다!👍

몇 가지 코멘트를 남겨보았습니다. 같이 의견 나눠보면 좋겠습니다.🤗

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/Common/Constants.swift
> +enum Constants {
공통으로 숫자와 문자열을 모아서 선언한 것은 좋습니다!👍
모든 숫자와 문자열을 모으기 보다는 용도 별로 나눠서 관리해보는 것은 어떨까요?
관련있는 부분(뷰, 셀, 파라미터 등)끼리 이름을 지어서 관리하면 또 다른 장점이 있을 것 같아요!
지금처럼 진행해도 무방합니다! 의견이 궁금합니다.😁

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/Extension/String+Extension.swift
> +    func strikeThrough() -> NSAttributedString {
`NSAttributedString` 를 활용해보셨네요. 좋습니다.👍

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/Model/OpenMarketProduct.swift
> +        func priceString(of price: Float) -> String {
가격을 통화 기호와 함께 문자열로 나타내는 메서드를 구현해보셨네요. 좋습니다.👍
`Currency` 타입 내에서 `priceString` 를 구현하신 이유가 궁금합니다!🤔

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/Utility/ImageLoader.swift
> +    static func loadImage(urlString: String?, completion: @escaping  (UIImage) -> ()) {
파라미터 정의 부분에 공백이 두번 들어갔어요!
이미지를 비동기적으로 처리하도록 구현해보셨네요. 좋습니다.👍

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/View/OpenMarketProductCellType.swift
> +protocol OpenMarketProductCellType {
리스트, 그리드 셀에서 사용할 수 있는 프로토콜 타입 구현 좋습니다!👍👍

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/View/OpenMarketProductCellType.swift
> +extension OpenMarketProductCellType {
익스텐션 디폴트 구현 좋습니다.👍

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +    }
리스트, 그리트를 표현하는 타입을 구현해보셨네요. 좋습니다.👍

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +        }
`fetchData` 의 `completion`도 `DispatchQueue.main.async` 에서 실행하는데
`DispatchQueue.main.async` 구문을 중복으로 사용하신 이유가 궁금합니다!🤔

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +    private func registerViews() {
이번 UI 구현에서 XIB를 사용하여 구현하신 이유가 궁금합니다!🤔

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +extension ProductListViewController: UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
`UICollectionViewDataSource` 프로토콜과 `UICollectionViewDelegateFlowLayout` 프로토콜을
역할과 가독성 측면에서 별도의 익스텐션에서 작성해보는 것은 어떨까요?🤔 의견이 궁금합니다.😁

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +            }
해당 부분은 리스트와 그리드가 동일해보입니다. 중복을 제거해보면 어떨까요!?

2022-02-04 14:41 UTC, zdodev commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
데이터를 미리 받아오는 기능을 구현해보셨네요. 좋습니다!👍
UIKit에서 제공하는 `Prefetching` 관련 기능을 확인해보셔도 좋을 것 같습니다!😁

2022-02-07 01:07 UTC, liam-777 commented on OpenMarket/OpenMarket/Common/Constants.swift
> +enum Constants {
네 세부적으로 나누는 것도 고민해보겠습니다 !

2022-02-07 01:12 UTC, liam-777 commented on OpenMarket/OpenMarket/Model/OpenMarketProduct.swift
> +        func priceString(of price: Float) -> String {
현재 `priceString` 이 cell에서만 사용되고 있지만 나중에 상세 화면같은 곳에서도 같은 함수가 필요하다고 생각했습니다. 따로 static 함수로 관리하는 것 보다 `Currency` 타입 내에서 관리시키게 더 깔끔하다고 생각했습니다 !

2022-02-07 01:19 UTC, liam-777 commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +        }
`fetchData` 에서 `DispatchQueue.main.async` 를 선언한 것을 깜빡했네요 ..😅

추가로 현재 코드는 `DispatchQueue.main.async` 구문을 `fetchData` 내에서 사용하고 있는데,
completion 전달 시점에서 직접 `DispatchQueue.main.async` 를 사용하는 것과 비교했을 때 어떤 방법이 더 자연스럽다고 보시는지 궁굼합니다!

2022-02-07 01:25 UTC, liam-777 commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +    private func registerViews() {
하나의 컬렉션 뷰에 두 개의 Cell을 사용하기 위해 XIB를 사용했습니다. 코드로만 구현하는 것은 시간도 많이 걸리고 직관적이지 않아서 이번 프로젝트에서 사용하지 않았습니다.

2022-02-07 10:04 UTC, zdodev commented on OpenMarket/OpenMarket/ViewController/ProductListViewController.swift
> +        }
개인적으로 전달시점보다는 `completion` 내에서 감싸는 것이 중복을 제거할 수 있다는 장점이 있다고 생각하면서,
모든 `completion`이 main 큐에서 실행될 이유가 없다면 비효율적일 수 있다는 생각도 듭니다.😅
두 가지 모두 적절하게 사용하면 좋을 것 같습니다!

2022-02-07 12:02 UTC, zdodev approved these changes
머지하도록 하겠습니다!

2022-02-07 12:03 UTC, merged