오픈마켓 [STEP2] Joel
yagom-academy/ios-open-market-new pull request #15
Opened 2022-02-07 07:34 UTC by inju2403

# STEP2
@wonhee009
안녕하세요 라자냐! 조엘입니다 :)
오픈마켓 STEP2 PR 요청드립니다!
</br>

# 구현한 것

1. UICollectionViewCompositionalLayout를 이용하여 LIST모양과 GRID모양의 컬렉션 뷰를 구성
2. ProductListViewModel을 이용하여 썸네일 이미지를 포함한 UI를 업데이트
    1. ProductListViewModel에서 NSCache를 사용하여 이미지 캐싱
3. Paging 구현 (scrollViewDidScroll 이용)
    1. bottom detection이 되면 scrollViewDidScroll()가 여러번 호출될 수 있으므로
    2. ProductListViewModel에서 isPaginating 프로퍼티를 두어서 paging api를 딱 한번만 호출하도록 구현
4. Loading UI 구현 (UIActivityIndicatorView)
    1. 첫 화면 로딩 & 페이징 로딩 시 UIActivityIndicatorView를 사용하여 로딩 UI를 구현
 </br>

# 궁금한 것

1. 컬렉션 뷰 셀에 비동기로 이미지를 꽂는 로직에 대해 궁금한 내용입니다! 1월20일 야곰 라이브 세션에서 다룬 Lazy Image Loading을 ProductCell.swift의 44번째 라인에서 구현했습니다. ProductListViewController(cellForItemAt - productCell.updateCell() ->  ProductCell.setImage( ) ->  productListViewModel.productThumbnailImage() -> productListViewModel.updateImage 로 이어지는 로직으로 구현하였습니다. 저는 셀에 이미지를 비동기로 꽂아줄 때
    1. 스크롤을 빠르게 내리면 셀이 재사용 됨에 따라 셀에 이미지를 비동기로 호출하는 함수 setImage()가 여러번 호출되고
    2. 먼저 호출된 setImage()가 나중에 호출된 setImage()보다 늦게 이미지 세팅이 완료되는 상황이 생긴다면(비동기때문에 생기는 문제)
    3. 셀에 원래 꽂혀야할 이미지가 아닌 다른 이미지가 꽂히는 현상이 일어나서
    4. ProductCell.swift의 44번째 라인에서 처럼 이미지를 로드하기 전 시점의 셀의 indexPath(cellIndexPath)와, 이미지를 로드한 후의 셀의 indexPath(collectionViewIndexPath)가 같을 때 이미지를 세팅하도록 했습니다. collectionViewIndexPath는 UICollectionView 레퍼런스를 이용해서 indexPath를 찾아오기 때문에 이렇게 이해했습니다. (라이브세션 영상을 보고 이렇게 이해했습니다)
    5. 그런데, 44번째 라인이 있을 때, 스크롤을 빠르게 아래로 했다가 다시 처음으로 돌아오면 이미지가 섞여있고, 오히려 44번째 라인을 없애면 셀의 이미지가 정상으로 꽂히는 것 같습니다. (segmentedControl의 LIST와 GRID를 번갈아가면서 빠르게 눌러도 이미지가 섞이는 현상이 있습니다 && 이미지들이 잠깐 다른 이미지였다가 다시 바뀌는 현상이 있습니다..)
    6. 이에 제가 컬렉션 뷰 셀과 이미지 로드에 대해서 잘못 이해했거나, ProductCell에서 44번째 라인의 구현이 잘못 되었거나, ProductListViewModel의 productThumbnailImage() 에서 이미지 캐싱하는 부분이 잘못 되었거나 등등 인것 같은데… 정확하게 어떤 부분이 잘못된지를 고민을 좀 해봤는데 잘모르겠습니다ㅜ. 라자냐가 이에 대해서 제게 깨달음을 주시면 정말 감사할 것 같아요!
2. ProductListViewModel에서 내부 프로퍼티와 메소드의 이름을 동일하게 하려할 때, 메소드에 파라미터를 아무것도 넣지 않으면 중복 선언이라 오류가 나서 파라미터를 가져야 하던데(이 때문에 불필요한 파라미터를 생성해야만 할거 같은데), 프로퍼티와 메소드의 이름을 동일하게 가져가려면 반드시 파라미터를 넣어야 하는지, 넣지 않고 해결하는 방법이 있다면 알고 싶습니다!
3. Cell의 UI를 코드로 구현했는데, ListCollectionViewCell에서 사용하는 스택뷰가 많아서 각각 파일로 분리해서 구현을 했는데, 이것보다 그냥 한 파일에 전부 구현하는 것이 더 좋을지 잘 모르겠습니다. 이에 대해 피드백을 받고 싶습니다!
4. 모던 컬렉션 뷰에서는 cell.accessories로 접근해서 셀의 우측에 > 표시를 넣어줄 수 있는 것 같은데, 모던 컬렉션 뷰를 사용하지 않았을 때는 어떻게 구현할 수 있는지 궁금합니다.
5. 그리드 뷰에서 밑으로 빠르게 스크롤 하면 이미지만 보이는 현상이 나타나는데 이 역시 왜 그런지 잘 모르겠습니다! 피드백 해주시면 감사하겠습니다!
6. 컬렉션 뷰 셀의 크기를 내부 프로퍼티들의 크기에 따라 동적으로 변경하고 싶은데, 지금 구현한 방법으로는 어떻게 해야할 지 잘 모르겠습니다. createListCompositionLayout() 내부에서 동적으로 변경하는 코드가 필요할 것 같은데 어떻게 하면 좋을지, 혹은 아예 다른 방법으로 UI 구성을 해보는게 좋을지.. 이에 대해 피드백을 얻고 싶습니다!
7. ProductListViewController의 45번째 라인에서 reloadData() 대신 invalidateLayout()을 호출하는 코드를 넣고 segmentedContorl을 GRID로 바꾸면 원래 LIST에서 로드되어 있던 셀들은 LIST에서의 모양대로 보이는데, 현재 구조에서는 reloadData()를 사용해야만 하는지 궁금합니다!(invalidateLayout()가 레이아웃만 바꾸는 걸로 봐서 성능이 좋아보여서 궁금합니다)
</br>

# 마무리
STEP3까지 완성해서 PR을 보내려했지만 중간에 고민하는 시간이 생각보다 길었기에 STEP2만 PR 보내게 되었습니다! STEP3는 다시 찬찬히 보는걸로 하겠습니다..ㅎㅎ

2022-02-07 12:23 UTC, wonhee009 requested changes
@inju2403 스텝2 수고하셨습니다👍
몇몇 코멘트 및 고민점1에 대해서 남겨두었습니다.
코멘트 중심으로 디벨롭하면서 고민점1에 대해서 같이 얘기해보면 좋을거 같습니다:)

<img width="602" alt="image" src="https://user-images.githubusercontent.com/30456206/152770778-cd895df6-c5a5-4743-926d-1b5e7f9274c0.png">
list->grid로 변경하면 offset이 살짝 밀리는거 같습니다. 확인 부탁드려요🙏

---

<img width="602" alt="image" src="https://user-images.githubusercontent.com/30456206/152771229-aeaa532e-5590-4de8-8a5c-8bf757f14315.png">
list에서 쭉 아래로 스크롤해서 다음 페이지들을 API 호출한 뒤 grid로 넘어가면 다음과 같이 레이아웃이 깨지는데 확인 부탁드립니다.🙏

---

고민점2
ProductListViewModel에서 내부 프로퍼티와 메소드의 이름을 동일하게 가져가야하는 이유가 있을까요?
프로퍼티와 메서드의 이름이 같아야한다면 역할 분리가 제대로 이뤄졌는지 한 번 더 생각해봐야할거 같습니다:)

고민점3
`ListNameAndPriceStackView'가 `ListPriceStackView`를 가지고 있는 식으로 연쇄적으로 가지고 있는거 같은데요.
이런 경우는 하나의 cell에 구현하는게 좋을수도 있을거 같습니다.
이후에 화면이나 스펙이 바뀌어서 화면을 수정해야할 때에 타고타고 들어가야하는 부분도 있을거 같습니다.

고민점4
`self.inputAccessoryView = UIView()`와 같은 방식으로 넣을 수 있을거 같습니다.

고민점5
빠르게 내리면서 레이아웃이 깨지는거 같은데요.
저도 좀 더 봐야겠지만 `createGridCompositionLayout()` 여기 요소들이 잘못 혹은 덜 지정된거 같습니다.

고민점6
> 컬렉션 뷰 셀의 크기를 내부 프로퍼티들의 크기에 따라 동적으로 변경

해당 내용에 대해서 좀 더 자세히 설명 부탁드립니다!

고민점7
<img width="333" alt="image" src="https://user-images.githubusercontent.com/30456206/152787416-0b985bcd-a706-4efb-90df-d9f8df327948.png">
45번째 줄에 아무 것도 없는데 혹시 좀 더 자세하게 설명 가능할까용

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/NetworkManager.swift
> +import UIKit
`Foundation`에서 `UIKit`로 바뀐 이유가 있을까요?.?

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Product/ProductList.swift
> +    var products: [Product]?
`var`로 바뀐 이유가 있을까요?.?

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Repository/ProductListRepositoryImpl.swift
> +        guard let url = OpenMarketURL.productList(pageNumber: pageNumber, itemPerPage: itemsPerPage).url else {
파라미터명도 `itemsPerPage`로 바껴야할거 같습니다:)

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
> +    var updateView: (Int) -> Void = {_ in }
```suggestion
    var updateView: (Int) -> Void = { _ in }
```

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
> +    var updateImage: (IndexPath?, UICollectionView?) -> Void = {_,_  in}
```suggestion
    var updateImage: (IndexPath?, UICollectionView?) -> Void = { _,_  in}
```

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
>      }
`ProductListViewModel`이라는 네이밍과 `var products: [Product]`를 가지고 있는거로 보아 해당 ViewModel은 리스트와 관련한 ViewModel로 이해했는데요.
어떠한 cell의 thumbnail image를 ViewModel이 가지고 있는 이유가 있을까요?

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
> +            self.cellIndexPath = indexPath
콜렉션뷰셀을 빠르게 스크롤한다면 `self.cellIndexPath`가 계속해서 바뀌고 이전에 요청했던 image는 바뀐 cellIndexPath 셀에 지정될거 같습니다.
이 부분이 조엘의 질문1과 관련있을거 같은데요.
다른 부분들 정리 후 다시 한 번 얘기해보면 좋을거 같습니다:)
'swift image async' 이런 키워드로 한 번 찾아보셔도 좋을거 같구요.

2022-02-07 12:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/Views/ProductListView/Cell/GridCollectionViewCell/GridCollectionViewCell.swift
> +    }
이 코드는 필요한 코드일까요?.?🤔

2022-02-08 00:22 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Networking/NetworkManager.swift
> +import UIKit
테스트를 해보다가 다시 바꾼다는걸 깜빡했네요 감사합니다 ㅎㅎ

2022-02-08 00:22 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Product/ProductList.swift
> +    var products: [Product]?
테스트를 해보다가 다시 바꾼다는걸 깜빡했네요 감사합니다 ㅎㅎ

2022-02-08 00:22 UTC, inju2403 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
>      }
셀들이 모여서 리스트를 구성하기 때문에 리스트 뷰모델에서 셀의 이미지 정보를 가지면서 바인딩하는게 좋다고 생각했습니다! 혹시 리스트뷰모델은 리스트 전체의 정보만 가지고 있는 것이 좋을까요? 그렇다면 셀을 위한 뷰모델을 하나 더 만드는게 좋을지 라자냐의 생각이 궁금합니다!

2022-02-08 00:22 UTC, inju2403 commented on OpenMarket/OpenMarket/Views/ProductListView/Cell/GridCollectionViewCell/GridCollectionViewCell.swift
> +    }
삭제했습니다! 감사합니다 :)

2022-02-08 02:46 UTC, inju2403 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
> +            self.cellIndexPath = indexPath
오전에 다시 보니 이미지를 캐싱하는 부분이 문제가 있었던거 같아서 수정했습니다! indexPath와 collectionView.indexPath(for: cell)가 같을 때 imageCache.setObject()를 해주도록 수정하니 이미지가 안섞이네요!

콜렉션뷰셀을 빠르게 스크롤한다면 self.cellIndexPath는 value를 캡쳐해서 이미지를 서버에서 받아온 후에도 바뀌지 않지만, collectionView와 cell은 레퍼런스를 캡쳐했기 때문에 이미지를 서버에서 받아오기 전과 받아온 후가 다를 수 있다고 이해했습니다. 따라서, indexPath와 collectionView.indexPath(for: cell)가 같을 때 이미지를 업데이트해주면 처음에 이미지 업데이트를 요청한 셀에 한 번만 업데이트를 해서 이미지가 안섞인다고 이해했는데, 혹시 제가 잘못 이해를 했는지 알고싶습니다! 그리고 혹시 이 방법 보다 효율적인 방법을 라자냐가 알고 계시다면 공유해주시면 감사하겠습니다 :)

2022-02-08 02:46 UTC, inju2403 commented
안녕하세요 라자냐! 피드백 감사합니다 :) 고민점 6은 레이블들의 크기에 따라서 동적으로 cell의 높이가 변경되는 것을 여쭤본 것이었습니다! 현재 글씨크기가 커지면 레이블이 …로 짤려 보여서요! 이 때문에 cell마다 다른 높이를 주고 싶었는데, createGridCompositionLayout()에서 동적으로 cell의 높이를 지정할 수 있는 방법에 대해 질문드렸습니다! 고민점 7은 제가 코드를 수정하다가 코드 라인을 잘못 말씀드렸네요 ㅜㅜ ProductListViewController의 40번째 라인입니다!

2022-02-08 09:09 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
>      }
리스트뷰 모델인데 개인 cell에 대한 image를 하나만 가지고 있는게 맞는가?라는 생각이 들어 리뷰를 남겼었습니다:)
필요하다면 셀을 위한 뷰모델을 만드는 것도 방법이라고 생각합니다.

2022-02-08 09:31 UTC, wonhee009 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
> +            self.cellIndexPath = indexPath
말씀하신 방법대로라면 이미지는 섞이지 않을거 같습니다:)
좀 더 효율적인 방법이라기 보단 개선할 수 있는 부분은 빠르게 스크롤한다면 상단에 보이던 셀 A의 썸네일 응답이 오지 않았는데 하단의 셀 Z로 이동한다면 A의 썸네일 호출을 취소하도록 개선할 수 있을거 같습니다.
다만 이 부분은 현재 구현하기에는 알아볼 부분이 좀 있을거 같으니 나중에 개선 혹은 공부할 부분으로 남겨두어도 될 것 같습니다!
(이후 좀 더 궁금하다면 KingFinsher라는 유명한 이미지 라이브러리가 있는데 한 번 까보셔도 좋을거 같습니다.)

2022-02-08 09:35 UTC, inju2403 commented on OpenMarket/OpenMarket/ViewModels/ProductListViewModel.swift
>      }
말씀해주신 대로 리스트 뷰모델이 cell의 이미지를 하나만 갖고 있는 것도 조금 어색하고,  cellIndexPath나 collectionView를 갖고 있는 부분도 많이 어색한거 같습니다! 셀을 위한 뷰모델을 하나 생성해주어서 거기서 처리하는게 좋을 것 같아서 수정했습니다!! 감사합니다 :)

2022-02-08 09:38 UTC, wonhee009 commented
고민점7
<img width="824" alt="image" src="https://user-images.githubusercontent.com/30456206/152959083-b7a6757f-0816-4036-bc2d-83a5294cd399.png">
이렇게 코드 적용했을때 말씀하시는 걸까요?

![image](https://user-images.githubusercontent.com/30456206/152959057-3f53927a-133a-4d7f-9040-7b684e64e187.png)
위와 같은 코드로는 그리드로 변환시에 reuse 되기전에는 위와 같은 화면으로 나옵니다.
collectionview의 layout은 변경되었지만 사용되는 셀은 여전히 listCell여서 그런데요.
혹시 제가 이해한 바가 맞을까요?.?

고민점6
"collectionview dynamic height" 이 키워드로 검색해보시면 좋을거 같습니다:)

2022-02-09 04:47 UTC, inju2403 commented
@wonhee009 
collectionview의 layout은 변경되었지만 사용되는 셀은 여전히 listCell여서 그런거였군요! 두 개의 셀을 사용할 때 저 코드에 대해서는 좀 더 고민해봐야겠네요 감사합니다! 
collectionview dynamic height에 대해 되게 좋은 방법들이 많은 것 같은데, 현재 구현에서는 이 방법이 가장 간단한 것 같아서 간단하게 수정했습니다! Grid에서는 좀 깨지는게 많아서 이 후에 다시 더 좋은 방법을 찾아봐야겠네요! 감사합니다 :)

2022-02-09 08:40 UTC, wonhee009 approved these changes

2022-02-09 08:40 UTC, merged