오픈마켓 [STEP2] hayden.chae
yagom-academy/ios-open-market-new pull request #16
Opened 2022-02-07 08:08 UTC by cms7371

안녕하세요 라자냐! 즐거운 명절 보내셨나요?
STEP2를 완료해서 리뷰 부탁드립니다!
## 구현내용
### 상단 디스플레이 스타일 컨트롤러
- SegmentedControlView를 이용하였으며, 최대한 피그마와 같게 커스텀을 하려했으나
기본 백그라운드가 회색으로 지정되어 있어 수정할 수 없는 문제가 발생했습니다. 이를 해결하려 다방면으로 알아봤으나, 
직접 하얀 이미지를 만들어 넣어주는 깔끔하지 못한 방법밖에 없어서, 야곰의 확인하에 그대로 두는 것으로 마무리 지었습니다.
- changedValue 액션을 이용하여 이벤트가 발생하면 값에 따라 ViewController의 isList Bool의 값을 바꾸어
화면 표시가 바뀌도록 했습니다
### CollectionView
- 메인 화면 구성은 권장 사항에 따라 Modern CollectionView를 이용해 만들어보려 노력했습니다
CompositionalLayout과 DiffableDataSource, Snapshot을 이용해서 구성했습니다.
- 리스트/그리드 전환은 isList 클래스 프로퍼티에 따라, CollectionViewLayout의 groupHeight와 column의 수가 바뀌도록 하였고,
CellResigtration을 ListCell과 GridCell에 해당하는 두개를 만들어 구현했습니다
### CollectionViewCell
- 우선 리스트/그리드의 셀의 컨탠츠가 동일하다고 생각했고, 같은 뷰들의 배치만 다른 것이라는 생각에 상속과 Delegate 패턴을 이용해봤습니다.
원래는 Abstract 클래스를 생각했으나 Swift에는 그런 것이 없어서 ProductCellBase를 만들어 공통된 컨탠츠, 동작을 정의하고
ProductCellLayoutDelegate를 만들어 각각의 형태에대한 Hierarchy, Constraint를 정의할 수 있도록 하였습니다
이를 ProductListCell, ProductGridCell에서 상속하여 각자의 모양을 정의할 수 있도록 했습니다.
### 비동기 데이터 로드
- Products 모델을 불러오는 것은 간단하게 이전의 정의한 MarketAPI를 이용하는 것으로 했습니다
원래는 하단까지 스크롤하면 다음 product를 추가적으로 불러오는 로직을 구현하고 싶었으나 이미 시간이 많이 지나
간단하게 구현했습니다
- 썸네일 이미지를 로드하는 것은 Data(contentsOf:, options:)를 이용하여, alwaysMapped 옵션을 활성화해 캐싱할 수 있도록 구현했습니다
이때 이 이니셜라이저의 blocking을 막기 위해 global 큐를 이용하여 userInteractive 우선순위로 처리할 수 있도록 했습니다
```swift
in ProductsViewController.swift

extension ProductCellBase {
    func lazyUpdateThumbnail(fromURL: String, indexPath: IndexPath) {
```
추가적으로 이를 ProductCellBase의 extension으로 정의한 것은 이미지를 로드하는 로직은 ViewController에 있는 것이 맞지만, ViewController의 함수로 정의하면 인자가 너무 많아지기에 extension을 이용해봤습니다.

## 궁금한점
### AbstractClass
ProductCell에서 상속을 이용하기로 결정했을 때 swift에서는 abstractClass가 없다보니 여러가지 방법이 있었습니다.
첫 번째로는 Protocol을 이용하는 방식이었습니다.
자식 클래스에서 정의해야할 동작을 Protocol로 정의하고 이를 채택하도록 하는 것이었습니다
근데 이 방법에는 부모클래스가 Protocol을 알지 못한다는 점,
그리고 자식 클래스가 실수로 Protocol을 채택하지 않아도 실수를 감지할 수 없다는 점이 큰 단점으로 느껴졌습니다
두 번째로는 fatalError를 이용하는 방법인데, 재정의해야 할 메서드들에 fatalError를 넣어 강제로 오버라이드 하도록 하는 것이었습니다
하지만 이 방법 역시 컴파일러단에서 감지하지 못하고, 런타임에 에러가 일어나기 전까지 모를 수 있다는 것이 별로라고 생각했습니다

결국 이 둘을 적절하게 이용해 protocol의 instance를 프로퍼티로 두고, 이를 set하는 메서드를 오버라이드하지 않으면
fatalError가 일어나도록 하는 방법을 이용해봤습니다만 여전히 찝찝함이 남아있습니다.
상속을 이용할 때 라자냐가 알고 계신 더 좋은 방법이 있을까요??
### CompositionalLayout의 NSCollectionLayoutDimension의 비정삭 동작
<img src="https://user-images.githubusercontent.com/65817235/152747756-f6b818a4-7baa-400f-b954-cfe1894079ac.png"  width="30%" height="30%">
처음 시도할 때 셀의 높이를 instrinsic 사이즈를 이용하여 self-sizing할 수 있도록 만들어봤습니다.
그런데 다음과 같이 일부가 intrinsic 사이즈가 아닌 estimated 높이로 적용되는 에러가 생겼습니다.
hugging priority도 건드려보고 여러가지 시도해봤는데 결국 해결하지 못해서 결국 고정 크기를 이용했는데
이 문제의 원인이 무엇인지 알 수 있을까요?

항상 꼼꼼한 리뷰 감사드립니다!!
cc. @wonhee009

2022-02-07 13:30 UTC, wonhee009 requested changes
@cms7371 스텝2 수고하셨습니다!👍
몇몇 코멘트 남겨두었으니 확인 부탁드립니다!🙏

AbstractClass
말씀 주신대로 protocol, superClass를 이용할 수 있을거 같습니다.
'부모클래스가 Protocol을 알지 못한다는 점'이 단점으로 느껴졌다고 하셨는데 부모클래스가 Protocol을 알아야하는 경우가 어떤 경우일까요?

CompositionalLayout의 NSCollectionLayoutDimension의 비정삭 동작
instrinsic 사이즈를 이용한 코드를 알 수 있을까요?.?

2022-02-07 13:30 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +    }
list->grid, grid->list로 바뀔때마다 해당 메서드가 호출되어 layout이 계속 생성될거 같습니다.
list, grid 레이아웃을 바뀔 때마다 생성하지 않고 미리 만들어둔 레이아웃을 반환하는건 어떨까요?.?

2022-02-07 13:30 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +}
page1에 대해서만 조회가 가능할거 같은데용. 이후 페이지는 조회 불가능한걸까요?.?

2022-02-07 13:30 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +#endif
요 코드는 어떤 이유로 들어가게 된걸까요?.?

2022-02-07 13:30 UTC, wonhee009 commented on OpenMarket/OpenMarket/Util/Float+extension.swift
> +}
Float extension에 정의하셨네용👍
Float 타입이라면 해당 메서드를 사용할 수 있을텐데요.
해당 기능은 모든 Float에 필요하다기 보다는 ProductCell에만 필요한 부분일거 같습니다.
Float에 정의해 모든 Float에 열려 있기 보다는 필요한 부분에만 열려 있는게 좋지 않을까 싶습니다:)

2022-02-07 13:30 UTC, wonhee009 commented on OpenMarket/OpenMarket/View/ProductCell/ProductCellBase.swift
> +    var showDetailMark: UIImageView!
!를 사용한 이유가 있을까요?.?

2022-02-07 13:35 UTC, cms7371 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +    }
createLayout은 configureHierarchy에서 collectionView를 정의할 때 한 번만 호출되고
changedValueDisplayStyleControlView의 collectionView.reloadData에서  isList에 따라 재구성 되는 것이기에
레이아웃이 재생성 되는 경우는 없을 것 같은데 혹시 제가 잘못 생각한 것일까요?

2022-02-07 13:35 UTC, cms7371 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +}
스크롤이 맨 아래로 내려갔을 때 다음 페이지를 로드하는 로직을 넣어보려했으나
STEP2에서 시간이 너무 지체된 것 같아 이정도만 진행했습니다 ㅠㅠ

2022-02-07 13:37 UTC, cms7371 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +#endif
코드로 UI를 구성할 때 SwiftUI의 Preview를 이용해 위와 같이 만들면
시뮬레이터로 돌리지 않아도 Xcode의 canvas에서 변경되는 레이아웃을 바로 확인할 수 있어서 이용해봤습니다

2022-02-07 13:40 UTC, cms7371 commented on OpenMarket/OpenMarket/View/ProductCell/ProductCellBase.swift
> +    var showDetailMark: UIImageView!
뷰의 경우 !를 붙이는 경우를 많이 보고 Interface Builder에서도 !를 사용해서
괜찮나...? 하고 이용해봤는데 혹시 부적절할까요..?

2022-02-07 13:43 UTC, cms7371 commented on OpenMarket/OpenMarket/Util/Float+extension.swift
> +}
피그마에서 제품 상세페이지에도 금액을 표시해야하는 부분이 있어서 부득이하게 더 넓은 범위로 빼놓게 되었습니다!

2022-02-07 13:48 UTC, cms7371 commented
> @cms7371 스텝2 수고하셨습니다!👍 몇몇 코멘트 남겨두었으니 확인 부탁드립니다!🙏
> 
> AbstractClass 말씀 주신대로 protocol, superClass를 이용할 수 있을거 같습니다. '부모클래스가 Protocol을 알지 못한다는 점'이 단점으로 느껴졌다고 하셨는데 부모클래스가 Protocol을 알아야하는 경우가 어떤 경우일까요?
> 
> CompositionalLayout의 NSCollectionLayoutDimension의 비정삭 동작 instrinsic 사이즈를 이용한 코드를 알 수 있을까요?.?

1. 다시 읽어보니 제가 말씀을 애매하게 드린 것 같은데 protocol만 이용할 때
부모 클래스를 자식클래스가 오버라이드했는데 실수로 protocol을 채택하지 않은 경우
이 실수를 사용자나 컴파일, 런타임에 감지할 방법이 없어서 적절하지 않을 수 있다고 생각했습니다

```swift
in ProductsViewController.swift

    func createLayout() -> UICollectionViewLayout {
        return UICollectionViewCompositionalLayout { _, _ in
            let column = self.isList ? 1 : 2
            let groupHeight = self.isList ?
                NSCollectionLayoutDimension.absolute(80) :  -->이 둘을 .absolute에서 .estimated 바꾸고
                NSCollectionLayoutDimension.absolute(250)  -->값을 현재값보다 더 크거나 작게 만들면 재현이 됩니다
            let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                                  heightDimension: .fractionalHeight(1.0))
            let item = NSCollectionLayoutItem(layoutSize: itemSize)
            let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                                   heightDimension: groupHeight)
            let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: column)
            group.interItemSpacing = .fixed(8)

2022-02-07 13:51 UTC, cms7371 commented on OpenMarket/OpenMarket/View/ProductCell/ProductCellBase.swift
> +    var showDetailMark: UIImageView!
개인적으로 생각했던 이유는 nil이 되면 안되는 뷰들의 경우 실수로 생성하지 않은 것을 런타임에라도 잡아주는 것이
적절할 것이라는 생각을 해서 이용한 것도 있었습니다

2022-02-08 05:03 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +    }
내부에 브레이크 포인트 찍으면 list->grid, grid->list 변경시에 계속해서 생성되고 있는거로 보입니다!

2022-02-08 05:03 UTC, wonhee009 commented on OpenMarket/OpenMarket/Controller/ProductsViewController.swift
> +}
아하 넵넵!👍

2022-02-08 08:59 UTC, wonhee009 approved these changes

2022-02-08 09:00 UTC, merged