오픈마켓 [STEP1] brendan
yagom-academy/ios-open-market-new pull request #5
Opened 2022-01-25 06:01 UTC by gjwlsdnr0115

@zdodev 
안녕하세요 Brendan입니다!!\
STEP1에서 구현한 사항은 크게 두가지 입니다.
- `NetworkService`
- `OpenMarketAPI`

리뷰 잘 부탁드리겠습니다~ 감사합니다~

# Network Service
- `NetworkService`는 서버와 통신하는 기능을 제공하는 구조체입니다.
- 해당 구조체는 `get<T: Codable>(from url: URL, as dataType: T.Type, completion: @escaping (NetworkResult<Any>) -> Void)` 메서드를 통해 GET 통신을 수행합니다.
- `get` 메서드는 URL과 디코딩할 데이터의 타입을 파라미터로 받고, comnpletion handler를 통해 통신 결과를 전달합니다.
- 또한 `healthChecker` API를 호출하는 경우에만 JSON이 아닌 `String` 형태로 데이터가 오기 때문에 이부분만 if문으로 따로 처리했습니다.

# Open Market API
- `OpenMarketAPI`는 Open Market API를 사용하도록 해주는 싱글톤 클래스입니다.
- 해당 객체는 `NetworkService` 구조체를 프로퍼티로 가지고 있고, 현재 세개의 메서드를 가지고 있습니다.
    - `checkHealth(completion: @escaping (NetworkResult<Any>) -> Void)`
    - `getProductList(pageNo: Int, itemsPerPage: Int, completion: @escaping (NetworkResult<Any>) -> Void)`
    - `lookupProductDetail(productId: Int, completion: @escaping (NetworkResult<Any>)`
- 각 메서드는 형식에 맞는 URL을 만들고 `NetworkService`의 `get` 메서드를 호출하여 API를 사용합니다.

# Network Result
- `NetworkResult`는 `enum`으로 구현했습니다.
- 서버와 통신하는 경우 그 결과가 기존에 원했던 데이터인지 에러인지 호출 시점에는 모르기 때문에 `Any`를 담고 있는 `NetworkResult`를 구현했습니다.
- 이를 통해 서버 통신을 성공적으로 마친 경우 해당 데이터를, 실패한 경우 에러 메세지를 `String`으로 전달합니다.
- 구현은 다음과 같이 했습니다.
    ```
    enum NetworkResult<T> {
        case success(T)
        case error(T)
    }
    ```

# 궁금한점
- `OpenMarketAPI`에서 직접 네트워킹을 하지 않고 `NetworkService`의 메서드를 호출해서 통신을 하다보니, 결과를 전달할 때 데이터가 두개의 escaping closure를 거쳐갑니다.
- ex) `getProductList` 메서드를 호출하면 `ProductListData`가 우선 `NetworkService`의 `get` 메서드의 클로져로 전달되고, 그것을 또 다시 `getProductList` 메서드의 클로져로 전달되어 이후 데이터를 사용하게 됩니다. (Unit Test 참고)
- 일반적으로 네트워크 통신은 비동기로 진행되기 때문에 클로져를 사용하려고 했지만 이렇게 두개의 클로져를 거쳐가는 것도 괜찮은 방식인 궁금해서 여쭤봅니다.

2022-01-25 13:06 UTC, zdodev requested changes
안녕하세요. @gjwlsdnr0115 !
오픈마켓 스텝1 PR 축하합니다!🎉

모델을 CodingKeys를 사용하여 잘 정의해주셨네요.👍
통신과 API 구현도 잘 작성해주셨습니다!

네트워크 통신을 구현하실 때 하나의 타입(or 클로저)로 구현하실 필요는 없습니다. 
지금처럼 역할을 나눠서 구현하신점도 많이 사용하는 방식입니다.👏👏

몇 가지 궁금점과 코멘트 남겨보았습니다. 궁금하신 점 의견 나눠보면 좋을 것 같습니다.

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarket/API/APIConstants.swift
> +    static let productLookupURL: String = baseURL + "api/products"
`baseURL` 마지막 `/`는 baseURL에 붙이는 게 좋을까요? path에 붙이는 게 좋을까요?🤔
URL 구조를 한 번 확인해보면 좋을 것 같아요! 지금도 좋습니다.😁

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarket/API/HTTPMethod.swift
> +enum HTTPMethod: String {
HTTP 메서드를 `enum`으로 표현해보셨네요. 좋습니다.👍

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarket/API/NetworkResult.swift
> +}
결과에 대한 타입을 만들어보셨네요. 좋습니다.👍
Swift의 `Result` 타입을 한 번 알아보셔도 좋을 것 같습니다!
구현하신 `NetworkResult` 과 `Result` 타입의 차이는 어떤 것이 있을까요?🤔

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarket/API/OpenMarketAPI.swift
> +    static let shared: OpenMarketAPI = OpenMarketAPI()
`OpenMarketAPI` 을 싱글턴으로 구현하신 이유가 궁금합니다!🤔

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarket/API/OpenMarketAPI.swift
> +    func checkHealth(completion: @escaping (NetworkResult<Any>) -> Void) {
다양한 API를 구현해보셨네요. 좋습니다.👍

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarket/API/NetworkService.swift
> +            completion(.success(decodedData))
`.success` 의 타입이 다양해지네요. 사용하는 측 코드에서 타입을 명확하게 알 수 있도록 구현해보는 것은 어떨까요? 의견이 궁금합니다!🤔
`NetworkResult` 코멘트를 참고하시면 좋을 것 같습니다.😁

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +class OpenMarketTests: XCTestCase {
실제 서버와 통신하는 테스트를 먼저 진행해주셨네요! Step 1-1이 생략된 것 같아요.😲
Mock 데이터를 통한 단위 테스트를 수행하는 단계를 작성해볼 수 있을까요?

2022-01-25 13:06 UTC, zdodev commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        sleep(1)
`sleep` 을 사용하신 이유가 궁금합니다.🤔

2022-01-26 05:11 UTC, gjwlsdnr0115 commented on OpenMarket/OpenMarket/API/APIConstants.swift
> +    static let productLookupURL: String = baseURL + "api/products"
API 명세서에서 baseURL이 단독으로 사용되는 경우가 없고 모두 뒤에 추가적인 path가 붙어서 `/`를 baseURL에 붙이는 것이 좋다고 판단했습니다!

2022-01-26 05:13 UTC, gjwlsdnr0115 commented on OpenMarket/OpenMarket/API/OpenMarketAPI.swift
> +    static let shared: OpenMarketAPI = OpenMarketAPI()
우선 앱 전역적으로 사용될 클래스여서 참조에 용이하게 하게 위해 싱글톤으로 구현했습니다.
또한 혹시 모를 상황을 대비해 앱 전역 어디에서 API 메서드를 호출하더라도 동일한 결과가 반환 되는 것을 보장하기 위해서 사용했습니다.

2022-01-26 05:14 UTC, gjwlsdnr0115 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        sleep(1)
테스트를 하는 상황에서 서버와의 통신이 완료 되기 전에 테스트 메서드가 종료되는 것을 방지하기 위해 사용했습니다.

2022-01-26 06:43 UTC, gjwlsdnr0115 commented
말씀하신 부분 참고하여 `Result` 타입에 대해서 찾아봤는데 제가 만든 `NetworkResult`보다 훨씬 깔끔하게 사용할 수 있을 것 같다는 생각이 들었습니다. 그래서 네트워크 관련 메소드들이 `Result`타입을 클로져로 전달하도록 구현했습니다. 또한 `NetworkError`을 `enum` 타입으로 만들어서 다양한 상황에 대한 에러 처리를 할 수 있도록 했습니다. 결과적으로 코드가 훨씬 직관적으로 읽히게 되는 것 같습니다!

2022-01-26 11:03 UTC, zdodev approved these changes
안녕하세요. @gjwlsdnr0115 !

스텝1 구현하시느라 고생하셨습니다. 
이번 스텝은 여기서 마무리하도록 하겠습니다.😁

2022-01-26 11:04 UTC, zdodev commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        sleep(1)
이런 상황에 사용할 수 있는 테스트 `XCTest` 가 있습니다. `asynchronous test` 에 대해서 한 번 확인해보시면 좋을 것 같습니다.😁

2022-01-26 11:04 UTC, merged