오픈마켓 [STEP1] Joel
yagom-academy/ios-open-market-new pull request #6
Opened 2022-01-25 06:55 UTC by inju2403

# Step1

@wonhee009 
안녕하세요 라자냐! 조엘입니다 :)
오픈마켓 STEP1 PR 요청드립니다!
</br>

# 구현한 것

* MVVM 패턴을 사용하여 구조 설계
        * Repository: Entity를 Fetch해와서 Model로 ViewModel에게 전달. 이때 NetworkManager를 이용
        * ViewModel: Repository로 부터 Model을 받아와서 ViewModel 내부에 갖고 있는 Model 프로퍼티를 갱신 후 View를 자동으로 업데이트
        * View(Storyboard + ViewController): 뷰모델에 있는 updateView 클로저와 didSet을 활용하여 View와 ViewModel 내부의 프로퍼티를 바인딩
</br>

* 타입 소개
    * Model
        * Repository
            * OpenMarketRepository: Entity를 Fetch해오는 메소드 정의
            * OpenMarketRepositoryRemoteDataSourceImpl: OpenMarketRepository을 채택하여 서버로부터 데이터를 받아옴
            * Product: 서버로부터 Json데이터를 받아와서 변환할 모델 타입들
        * OpenMarketRepositoryInjection: 뷰모델에서 내부 프로퍼티로 갖고 있는 OpenMarketRepository 타입에 OpenMarketRepositoryRemoteDataSourceImpl을 주입하는 타입
        * Networking
            * 네트워크와 관련된 타입들
            * HTTPMethod: HTTP Method를 String 값으로 반환할 수 있는 enum 타입 
            * JSONFileDecoder: Json File을 모델로 변환해주는 타입
            * OpenMarketURL: openmarket url 정보를 담고 있는 enum타입 
            * NetworkError: Error을 채택하여 네트워킹 에러를 처리할 수 있는 enum 타입 
            * NetworkManager: URLSession을 통해서 네트워킹을 진행하는 타입. repository에서 사용함
    * View
        * 아직 작성하지 않았습니다!
    * ViewModel
        * ProductListViewModel: 상품 리스트에 대한 뷰모델
        * ProductDetailViewModel: 상품 상세에 대한 뷰모델
    * Constant
        * 상수 파일. static 변수를 이용하여 관리
        * 아직 작성된 코드는 없지만 곧 작성하여 사용할 예정입니다!
</br>

# 궁금한 점

1. URLSession을 사용하여 네트워킹을 해보는 게 처음이라, 어떻게 사용하는 것이 클린 아키텍쳐를 구성하는 방법인지 잘 모르겠습니다! 그래서 어떻게든 효율적이게 짜보려고 노력해봤지만 저에게 하루라는 시간은 너무 짧은거 같습니다 ㅜㅜ 라자냐가 이에 대해서 피드백해주시면 너무 감사할 것 같아요 ㅎㅎ
2. 테스트 코드는 처음에 진행했던 성적관리 프로젝트 이후로 처음이라, 제가 작성한 네트워킹에 대한 테스트 코드가 적절한지 코드인지 잘 모르겠습니다. 좋은 테스트 코드를 작성하기 위해서 어떤 것이 필요할 지 알고 싶습니다!
3. 이전 프로젝트에서도 소대와 잠시 이야기를 나누었지만, OpenMarketRepository와 뷰모델 등에서 함수에 productList, product와 같은 네이밍을 사용하고 있는데 이러한 네이밍을 사용하는 것에 대해 이야기를 나누고 싶습니다. Swift API Design Guidelines 이외에 코딩 컨벤션을 알아보다가 알게된 문서인 https://github.com/StyleShare/swift-style-guide 를 참고하여 작성한 네이밍인데, 함수 앞에는 되도록 get을 붙이지 않고 받아오는 타입을 그대로 사용하는 것을 좋은 예로 보고 있는 것 같습니다. 이에 대해 코딩 컨벤션이 약속되어진 팀에서는 정말 깔끔한 코드가 될 것 같은데, 혹시 이에 대한 코딩 컨벤션이 약속되어 있지 않은 곳에서도 이처럼 사용하는 것이 괜찮을 지에 대한 라자냐의 생각이 궁금합니다!
4. 뷰모델에서 사용하는 프로퍼티인 repository는 OpenMarketRepository 프로토콜을 채택하고 OpenMarketRepositoryInjection을 통해서 OpenMarketRepositoryRemoteDataSourceImpl를 주입받고 있는데요, 뷰모델에서 repository가 어떤 곳에서 데이터를 받아오는지 알 필요가 없다고 생각하여 이런식으로 구성하였는데 이게 괜찮은 설계인지 잘 모르겠습니다. 라자냐는 어떻게 생각하시는지 궁금합니다!
</br>

# 마무리
오픈 마켓 프로젝트가 지금까지 해온 프로젝트 중에 기간이 가장 긴거 같아요. 긴 기간 동안 잘 부탁드리겠습니다 🚀
</br>

2022-01-25 11:29 UTC, wonhee009 requested changes
@inju2403 스텝 1 수고하셨습니다!
클린 아키텍쳐의 향기가 느껴지는 PR였습니다.
몇몇 코멘트 남겨두었으니 확인 부탁드립니다~

1. [WWDC 영상](https://developer.apple.com/videos/play/wwdc2018/417/)이나 [이런](https://developer.apple.com/documentation/foundation/localizederror) 자료들도 확인해보시면 좋을거 같습니다. 

2. 좋은 테스트 코드라... 저도 아직 더 좋은 테스트 코드에 대해서는 어려운거 같아요. 다만, 이전에 TDD에 대해서 공부했을때 생각했던 부분은 메서드를 각자의 역할에 충실하게 작동하도록 하고, 단위를 작게 가져가야 좀 더 유의미한 테스트를 할 수 있지 않을까? 였던거 같습니다.

3. 저도 productList, product 이렇게 네이밍하는거 좋습니다! 코딩 컨벤션이 약속되어 있지 않은 곳에서도 사용해도 되지 않을까요? (하지만 아마 대부분 컨벤션 혹은 흐름이란게 있을듯 하니...)

4. 이 부분은 코멘트 반영하면서 좀 더 얘기해보면 좋을거 같습니다:)

5. 실제로 사용할때에는 
```swift
viewModel.productList
repository.productList
``` 
이렇게 사용되어 질거 같은데요.
어느 부분에서 호출하는지 명확하기 때문에 괜찮지 않을까 생각이 드네요.

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/BuildLogic/OpenMarketRepositoryInjection.swift
> +    private init() {}
싱글톤이 아닌데 private으로 init을 선언하신 이유가 궁금합니다!

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/JSONFileDecoder.swift
> +    static func decodeJson<T: Decodable>(_ decodingType: T.Type, from jsonData: Data) -> T? {
`JSONFileDecoder.decodeJson()`으로 사용할거 같은데요.
`decode()`여도 의미 전달이 가능할거 같습니다!😀

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/JSONFileDecoder.swift
> +struct JSONFileDecoder {
`JSONDecoder`는 어떨까요?
제이슨 파일만 해당하는 부분은 아닌거 같아서용🤔

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/NetworkError.swift
> +    }
[이런 것](https://developer.apple.com/documentation/foundation/localizederror)도 사용해 볼 수 있을거 같아요🤔

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/OpenMarketURL.swift
> +    case product(Int)
현재는 프로젝트에서 사용하는 url의 수가 적고, url에 붙는 param들의 갯수도 적은데요.
만약, 이후에 url에 붙는 param들의 갯수가 많아진다면 `APIAddress(Int, Int, Int, Int)`이런 식으로는 대응하기 힘들거 같습니다🥲
사용처에서는 
```swift
OpenMarketURL.APIAddress(Int, Int, Int, Int)
```
이렇게만 보여서 어느 위치에 어떤 value를 넣어야 하는지 알기 위해서는 다시 enum을 확인해야할 것 같습니다.

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Product/Product.swift
> +    }
good👍

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Product/ProductImage.swift
> +    let thumbnailUrl: String
이름이 url여서 타입도 url일 것 같습니다.
`urlString`같이 뒤에 타입을 알 수 있도록 해주는건 어떨까용?🤔

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Product/Product.swift
> +    let vendors: Vendor?
vendors라는건 Vendor가 여러개 들어올 수 있는걸까요?

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Product/ProductList.swift
> +    let pages: [Product]?
pages보다는 Product임을 알 수 있는 네이밍이 더 좋을거 같습니다.
실제로 사용할때에는
```swift
productList.pages[0].price
```
이런 식으로 제품의 가격을 가져올게 될텐데 이후 작업자가 봤을때에는 pages가 어떤건지 다시 한 번 확인해봐야하지 않을까요?🤔

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        let productId = 522
productId가 522인 상품이 삭제되면 어떻게 되나용?👀

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Repository/OpenMarketRepositoryRemoteDataSourceImpl.swift
> +struct OpenMarketRepositoryRemoteDataSourceImpl: OpenMarketRepository {
`RemoteDataSource`는 없어도 의미 전달이 되지 않을까?라는 생각이 들었습니다.

2022-01-25 11:29 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Repository/OpenMarketRepository.swift
> +    func deleteProduct()
프로젝트에서 사용하는 API가 늘어나면 해당 메서드들이 무한정으로 늘어날거 같은데요.
```swift
protocol ProductListRepository { ... }
protocol ProductRepository { ... }
```
이렇게 API 주체에 따라 나눠보는건 어떨까요?

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/BuildLogic/OpenMarketRepositoryInjection.swift
> +    private init() {}
Injection타입이 단순히 repository를 주입해주는 역할을 하기 때문에, 인스턴스를 생성할 필요가 없다고 생각해서 방지하기 위해서 원래는 넣었습니다! 그런데 생각을 해보니 private init() {}을 사용하는 타입은 싱글톤이구나~ 라고 생각할 수도 있다는 생각이 들어서 제거하였습니다! 혹시 제가 생각한 것처럼 private init() {}을 사용하는 타입은 주로 싱글톤일까요? 만약 그렇다면 이 코드가 없는게 좋을 것 같아서 제거하였습니다!

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Networking/JSONFileDecoder.swift
> +    static func decodeJson<T: Decodable>(_ decodingType: T.Type, from jsonData: Data) -> T? {
decode()로 변경하였습니다 좋은 피드백 감사합니다 :)

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Networking/JSONFileDecoder.swift
> +struct JSONFileDecoder {
JSONDecoder가 [이것](https://developer.apple.com/documentation/foundation/jsondecoder)과 이름이 겹쳐서 사용할 수 없는 것 같습니다 ㅜㅜ 혹시 같은 이름을 사용할 방법이 있을까요? 일단 이름은 JSONConverter로 변경했는데, 이유는 후에 인코딩에서도 사용할 거라 생각했기 때문입니다!

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Networking/NetworkError.swift
> +    }
정말 좋은 꿀팁 감사합니다 :) LocalizedError를 적용한 코드 추가했습니다.
궁금한 것은 혹시 제가 var description으로 만든 것과 
LocalizedError를 확장하여 errorDescription를 사용하는 것의 어떤 명확한 차이가 있는지 궁금합니다!

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Networking/OpenMarketURL.swift
> +    case product(Int)
```case productList(pageNumber: Int, itemPerPage: Int)``` 파라미터에 value 이름을 명시하도록 수정하였습니다! 감사합니다 ㅎㅎ

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Product/ProductImage.swift
> +    let thumbnailUrl: String
thumbnailUrlString으로 수정하였습니다! 원래 CodingKey를 스네이크 케이스를 카멜케이스로 바꾸는 용도로만 사용하는 줄 알았는데, 혹시 이렇게 클라이언트에서 적절하다고 생각하는 이름으로 커스터마이징을 하는게 더 좋은 코드일지 궁금합니다! (서버와의 소통에서 파라미터의 이름이 다르면 소통하는 것이 좀 힘들지 않을까해서 궁금합니다 ㅎㅎ)

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Product/Product.swift
> +    let vendors: Vendor?
이 또한 서버에서 보내주는 json 이름인 vendors를 그대로 사용했었는데, vendor로 변경했습니다!

2022-01-25 13:26 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Product/ProductList.swift
> +    let pages: [Product]?
pages -> product로 변경하였습니다!

2022-01-25 13:27 UTC, inju2403 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        let productId = 522
그러게요..ㅋㅋㅋ 이 부분은 생각을 못해봤네요 ㅜ 단지 api 명세에 있는 id로 테스트해보자~ 라는 생각으로 522를 사용하였는데, 혹시 더 좋은 방법이 있을까요??

2022-01-25 13:27 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Repository/OpenMarketRepositoryRemoteDataSourceImpl.swift
> +struct OpenMarketRepositoryRemoteDataSourceImpl: OpenMarketRepository {
그냥 Impl로 변경하였습니다! 이 부분도 조금 궁금한 점이 있었는데, repository라는 프로토콜을 사용하는 이유가 서버로부터 데이터를 받아오는지, 내장 DB를 사용하는지 등등을 다른 타입에서는 모르게 하기 위해서라고 알고 있었는데, 혹시 그냥 Impl로 사용하고 이 타입 안에서 서버로부터 데이터를 받아오는 혹은 내장 DB를 사용하는 로직을 구현하는 것이 일반적인 방식일까요? 그렇지 않다면 RemoteDataSource 혹은 DeviceDB같은 네이밍을 포함하는 것도 좋을 것 같은데(구현체를 하나를 만들고 그 안에서 여러 방법을 구현하기 vs 구현체를 여러개 만들기) 혹시 어떻게 생각하시는지 궁금합니다! ㅎㅎ

2022-01-25 13:27 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Repository/OpenMarketRepository.swift
> +    func deleteProduct()
좋은 피드백 감사합니다!! 적용했습니다! ㅎㅎ

2022-01-25 13:28 UTC, inju2403 commented
@wonhee009
라자냐 안녕하세요~ 좋은 피드백 감사합니다!
피드백 주신 내용 반영해서 커밋했고, 다른 궁금한 사항들 작성했습니다! 시간 나실 때 확인 부탁드리겠습니다 ㅎㅎ

2022-01-26 10:00 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/JSONFileDecoder.swift
> +struct JSONFileDecoder {
아하! JSONDecoder에 대해서 잊고 있었네요ㅠ_ㅠ 네네 Converter도 좋은거 같습니다👍

2022-01-26 10:02 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/NetworkError.swift
> +    }
저희는 LocalizedError에서 errorDescription만 사용하긴 하지만 애플에서 제공하는 다른 프러퍼티나 메서드를 사용할때에는 좀 더 좋지 않을까요?🧐

2022-01-26 10:03 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/OpenMarketURL.swift
> +    case product(Int)
이후에 파라미터들이 늘어난다면 관리하기 힘들지 않을까요?🤔
이런 파라미터들을 하나의 struct로써 관리하는 방법도 있습니다!

2022-01-26 10:04 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Product/ProductImage.swift
> +    let thumbnailUrl: String
서버와의 소통도 중요하지만 클라이언트 프로젝트에서 계속해서 사용되는 네이밍이므로 모두가 이해 가능한 네이밍이 좀 더 좋지 않을까요? 실제로도 좀 더 이해하기 편한 네이밍으로 바꿔서 사용하기도 하고요:)

2022-01-26 10:05 UTC, wonhee009 commented on OpenMarket/OpenMarketTests/OpenMarketTests.swift
> +        let productId = 522
Mock data를 만들어서 테스트 하는 방법도 있을거 같습니다:)

2022-01-26 10:12 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Repository/OpenMarketRepositoryRemoteDataSourceImpl.swift
> +struct OpenMarketRepositoryRemoteDataSourceImpl: OpenMarketRepository {
Repository가 어디서 가져오는지 숨기기 위한 프로토콜이라고 말씀하신거 같은데요. RemoteDataSource를 붙이면 어디서 가져오는지 알 수 있지 않을까요?

2022-01-26 10:13 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/BuildLogic/OpenMarketRepositoryInjection.swift
> +    private init() {}
네 싱글톤일때 주로 사용하는 것 같습니다:)

2022-01-26 10:39 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Networking/OpenMarketURL.swift
> +    case product(Int)
그러면 각 케이스 별로 구조체를 만들어서 관리하는 방법일까요?? 예를 들면 ProductListURLParam, ProductURLParam 이런식으로 ..??

2022-01-26 10:39 UTC, inju2403 commented on OpenMarket/OpenMarket/Models/Repository/OpenMarketRepositoryRemoteDataSourceImpl.swift
> +struct OpenMarketRepositoryRemoteDataSourceImpl: OpenMarketRepository {
뷰모델이 갖고 있는 Repository프로토콜을 채택한 프로퍼티에 실제로 타입을 주입하는 건 RepositoryInjection 안에서 하기 때문에 뷰모델에선 모르기 때문에 모른다고 생각했습니다! 실제로 RepositoryImpl객체를 주입하는 건 RepositoryInjection 안에서 해서요!

2022-01-27 03:23 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Networking/OpenMarketURL.swift
> +    case product(Int)
네넵 그렇게 struct로 관리하면 URL을 생성하기 위해 작업자가 채워줘야하는 프로퍼티들이 명확해지기도 합니다:)
해당 사항은 이런게 있다로 넘어가고 현재는 지금을 유지해도 괜찮을거 같습니다.

2022-01-27 03:30 UTC, wonhee009 commented on OpenMarket/OpenMarket/Models/Repository/OpenMarketRepositoryRemoteDataSourceImpl.swift
> +struct OpenMarketRepositoryRemoteDataSourceImpl: OpenMarketRepository {
네 이해했습니다:)
그렇다면 이대로 유지해도 될거 같습니다!

2022-01-27 03:31 UTC, wonhee009 approved these changes
@inju2403 스텝1 수고하셨습니다!
다음 스텝에서 만나요

2022-01-27 03:31 UTC, merged