오픈마켓 [STEP1] hayden
yagom-academy/ios-open-market-new pull request #7
Opened 2022-01-25 07:23 UTC by cms7371

안녕하세요 라자냐!
이번 프로젝트 리뷰를 부탁드리게 된 헤이든이라고합니다.
잘부탁드립니다!!

## 구현 내용
### API Models - Page, Product, ProductImage, Vendor
```swift
struct Product: Decodable {
    ...
    let images: [ProductImage]?
    let vendor: Vendor?
    ...
```
- 네트워크의 응답으로 받는 JSON을 모델로 구현했습니다. 위처럼 경우에 따라 존재하지 않는 프로퍼티는 옵셔널로 하여
추후 다른 API 메서드가 추가되더라도 추가적인 모델이나 수정이 필요하지 않도록 만들었습니다.
```swift
    func testDecodingProductWithVenderAndImage() throws {
        // given and when
        let jsonData = NSDataAsset(name: "json_productExample")!.data
        // then
        XCTAssertNoThrow(try JSONCoder.shared.decode(from: jsonData) as Product)
        // check
        let product: Product = try JSONCoder.shared.decode(from: jsonData)
        print(product)
    }
```
- 단위 테스트는 API 문서로부터 예시 JSON을 얻어 Asset에 저장하였고, 이를 불러 직접 변환해 에러가 나는지를 체크했습니다
### HTTPManager
- API를 이용할 때 중복된 코드를 제거하고, 네트워크 에러에 대한 핸들링과 추상화를 위해 정의하여 통신에 대한 책임을 지도록 했습니다
```swift
static func get(url: String, path: [String]?, query: [String: Any]?, 
                          completionHandler: @escaping (Data) -> Void) 
    ....
    let getTask = URLSession.shared.dataTask(with: request) { (data, response, error) in
        if let error = error {
            print("HTTPManager: error - \(error.localizedDescription)")
            return
        }
```
- HTTP 메서드를 기준으로 함수를 구성하였고, 추후 POST나 PATCH에 대한 것도 정의할 예정입니다
### MarketAPI
```swift
    static func getProducts(pageNumber: Int, itemCount: Int = 20, completionUIHandler: @escaping ([Product]) -> Void) {
        HTTPManager.get(url: baseURL, path: basePath,
                        query: ["page_no": pageNumber, "items_per_page": itemCount]) { jsonData in
            do {
                let fetchedPage: Page<Product> = try JSONCoder.shared.decode(from: jsonData)
                DispatchQueue.main.async {
                    completionUIHandler(fetchedPage.items)
                }
            } catch {
                print("MarketAPI: Failed decoding page of products JSON")
            }
        }
    }
```
- MarketAPI는 HTTPManager를 이용하여 각각의 API를 메서드로 정의해 그에 맞는 형식으로 Request가 보내지고,
받은 데이터를 MainQueue에서 핸들링 하게 처리하도록 구현했습니다
- 그리고 단위 테스트를 구현해 각각의 메서드들이 제대로 결과를 받아오는지 테스트할 수 있도록 했습니다
- 이때 테스트에서 MainQueue에 결과를 던져주는 것과 sleep이 충돌이 일어나 XCTestExpectation을 이용해서 지연이 일어나도록 했습니다.
## 고민되는 점
- 이번 스탭에서 가장 고민되었던 것은 API를 호출하는 과정에서 일어날 수 있는 수많은 에러 처리에 관한 것이었습니다.
URL을 만들 때, HTTP request를 보낼 때, JSON으로 파싱할 때 등 너무 많은 분기점이 있었고,
이들을 어떻게 처리할지는 고민하는데에 가장 많은 시간을 할애했습니다.
한가지 찾은 좋은 방법은 Swift Concurrency를 이용하는 것이었는데, 이를 이용하면 기존 동기 함수와 다름없이
에러를 흐르게 할 수 있다는 장점이 있었지만 타겟 os 때문에 이용하지는 못했습니다...
그래서 생각한 방법이 각각의 레벨에서 발생하는 문제를 스스로 처리하는 것이었습니다
HTTPManager-MarketAPI-ViewController의 플로우 속에서 자신의 차례에서 일어나는 에러를 직접 처리하고,
하위 객체는 모르도록 하는 것이 흐름을 파악하기도, 디버깅하기도 쉽지 않을까라는 생각을 하여 지금과 같은 구조를 생각했습니다.
이것이 적절한 판단인지 라자냐의 생각을 들어보고 싶습니다!
추가적으로 현재는 이용자의 경험을 위해 멈추지 않고 에러를 print하는 방향으로만 핸들링하고 있는데,
이것이 적절한지, 더 나은 방향이 있는지 여쭤보고 싶습니다(단순 error를 throw하는 것은 비동기 상황에서 의미가 없다고 생각했습니다)
- 요구사항에 주어진 (네트워크 상황과 무관한 네트워킹 데이터 타입의 단위 테스트)가 mock 테스트를 말하는 것이 맞죠...?
처음에는 단순히 JSON을 모델로 변환하는 테스트를 생각했는데 검색하다보니 가짜 URLSession을 넣어 진행하는 테스트를 찾았습니다
이 부분은 이해하고 제대로 진행하기에는 시간이 오래 걸릴 것 같아서 추후 여유가 되면 진행해보겠습니다...

cc. @wonhee009

2022-01-25 11:59 UTC, wonhee009 requested changes
@cms7371 스텝1 수고하셨습니다!🎉
몇몇 코멘트 남겨두었으니 확인 부탁드립니다.🙏

- 저는 에러 중에는 사용자가 알아야 하는 에러/개발자가 알아야 하는 에러/에러가 발생했지만 무시할 수 있는 에러가 있다고 생각합니다. 사용자가 알아야 하는 에러라면 해당 에러가 어떻게든 View단까지 도달해야하겠죠. 개발자가 알아야 하는 에러는 사실상 디버그용으로 print든 다른 에러 툴을 사용할 수 있을 것이고, 무시할 수 있는 에러는 때에 따라서 추가 처리가 필요할 수 있어 View단까지 도달해야하는 경우도 있을 것 같습니다. 현재 정의되어 있는 여러 에러들을 화면에 보여줘야할 필요가 있나?를 한 번 생각해보시는 것도 좋을 것 같습니다:)
- mock을 이용하는 방법도 하나의 방법이라고 생각합니다:) 실제 프로젝트에서는 mock을 사용해 테스트할 수 있는 경우도 있고, 가짜 URL을 넣어서 테스트할 수 있는 경우도 있어서 뭐가 딱 정답이다는 없는 것 같습니다.
- 코멘트에도 남겼지만 `MarketAPI`, `HTTPManager`의 역할을 다시 한 번 생각해보셨으면 좋겠습니다:)

2022-01-25 11:59 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/Page.swift
> +struct Page<T: Decodable>: Decodable {
제네릭을 사용한 이유가 따로 있을까요?

2022-01-25 11:59 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/ProductImage.swift
> +    let thumbnailURL: String
이름이 url여서 타입도 url일 것 같습니다.
urlString같이 뒤에 타입을 알 수 있도록 해주는건 어떨까용?

2022-01-25 11:59 UTC, wonhee009 commented on OpenMarket/OpenMarket/Util/JSONCoder.swift
> +    }
싱글톤을 사용하셨네요👍
```swift
class JSONCoder {
  static func decode<T: Decodable>() { ... }
}
```
싱글톤을 사용하는 것과 위의 코드처럼 static 메서드를 사용하는 것에 어떤 차이가 있을까요?🤔

2022-01-25 11:59 UTC, wonhee009 commented on OpenMarket/Podfile.lock
> +  - SwiftLint (0.45.1)
린트를 사용해보셨군영👍

2022-01-25 11:59 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/MarketAPI.swift
> +    private init() { }
init에 private으로 막아놓은 이유가 있을까요?🤔
현재 모든 프로퍼티나 메서드가 static으로 사용되고 있는데요.
class인 이유도 궁금합니다.

2022-01-25 11:59 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/MarketAPI.swift
> +    }
`MarketAPI`라는 이름만 보면 관련 API를 생성해주거나 API와 관련한 역할을 할 것 같습니다.
해당 메서드는 `HTTPManager`에 API 생성부터 데이터를 가져오는 역할을 맡기고, 여기서는 json을 model로 변환하는 작업과 UI 업데이트를 담당하고 있는것 같습니다.
또한, 이런 과정 속에서 completionHandler가 반복적으로 엮이고 있고요.

이런 과정들을 좀 더 떼어내 보는건 어떨까요?
- `MarketAPI`에서는 url, path, query를 이용해 API를 생성
- HTTPManager는 API를 주입 받아서 데이터 fetch
- VC에서 model로 변환 및 UI 업데이트

이런 식으로요👀

2022-01-26 00:17 UTC, cms7371 commented on OpenMarket/OpenMarket/Model/Page.swift
> +struct Page<T: Decodable>: Decodable {
이전에 진행했던 프로젝트에서도 page 형태로 API 응답이 내려오는 경우를 보아서
Page가 Product만을 items로 갖는 것이 아닌 더 포괄적인 개념이라 생각해 제네릭으로 하는 것이 맞다고 판단했습니다

2022-01-26 00:20 UTC, cms7371 commented on OpenMarket/OpenMarket/Model/ProductImage.swift
> +    let thumbnailURL: String
그 부분은 미처 생각하지 못했는데 좋은 것 같습니다! 더 명시적으로 수정해보겠습니다😁

2022-01-26 00:39 UTC, cms7371 commented on OpenMarket/OpenMarket/Util/JSONCoder.swift
> +    }
우선 싱글톤으로 구현한 이유는
JSONDecoder의 Date decoding과 같은 것들을 추후 커스텀할 필요가 있을 것는 판단때문이었습니다
그렇게 되면 이렇게 커스텀된 JSONDecoder를 static이 아닌 인스턴스가 갖도록 하는 것이 옳다고 생각했습니다
비슷한 맥락으로 질문을 생각해보면 static 메서드, 프로퍼티는 인스턴스가 아닌 타입에 저장된다는 차이가 있고
그렇기에 non-static 멤버에 접근할 수 없다는 특징을 말씀드릴 수 있을 것 같습니다
하지만 원리가 아닌 싱글톤과 static 클래스의 동작 자체만 본다면
결과적으로는 큰 차이가 없지 않나 하는 생각도 들어서 이 부분은 라자냐의 생각을 여쭤보고 싶습니다

2022-01-26 00:42 UTC, cms7371 commented on OpenMarket/OpenMarket/Model/MarketAPI.swift
> +    private init() { }
다른 언어를 쓰던 습관으로 생각없이 class로 구현했는데 struct로 변경해도 될 것 같습니다
init을 막은 것은 static으로 사용되는 클라스라 추후 누군가가 실수로 인스턴스를 만드는 경우를 방지해야한다고 생각해서 그랬습니다!

2022-01-26 00:46 UTC, cms7371 commented on OpenMarket/OpenMarket/Model/MarketAPI.swift
> +    }
저도 연쇄적으로 handler가 엮이는 것이 찝찝했는데 좋은 아이디어인 것 같습니다!!
viewController가 복잡해질 것이라 생각해서 최대한 이전 작업을 모르도록 만들려는 생각을 했는데
라자냐의 말씀대로 viewController에게 변환과 업데이트를 넘긴다면 더 깔끔한 구조가 될 것 같습니다!

2022-01-26 06:34 UTC, cms7371 commented
라자냐가 주신 피드백 기반해서 리팩터링 진행했습니다!

### Page
```swift
struct Page<Item: Decodable>: Decodable {
    ....
    let hasNext: Bool
    let items: [Item]
```
Page가 item을 감싸는 모델이라는 것을 더 명시적으로 표현할 수 있도록 제네릭 이름을 바꿔보았습니다
### ProductImage
```swift
struct ProductImage: Decodable {
    ....
    let urlString: String
    let thumbnailURLString: String
    ....
    enum CodingKeys: String, CodingKey {
        case id
        case urlString = "url"
        case thumbnailURLString = "thumbnail_url"
```
이미지의 url이 String임을 알기 편하게 프로퍼티 이름을 바꿨습니다
### Market API
```swift
struct MarketAPI {
    private init() { }

    static let baseURL = "https://market-training.yagom-academy.kr"
    static let basePath = ["api", "products"]

    static func getProducts(pageNumber: Int, itemCount: Int = 20, completionHandler: @escaping (Data) -> Void) {
        HTTPManager.get(url: baseURL, path: basePath, query: ["page_no": pageNumber, "items_per_page": itemCount],
                        completionHandler: completionHandler)
    }

    static func getProduct(id: Int, completionUIHandler: @escaping (Data) -> Void) {
        HTTPManager.get(url: baseURL, path: basePath + ["\(id)"], query: nil, completionHandler: completionUIHandler)
    }
}
```
기존 JSON 변환과 메인 스레드로 결과 동작을 던져주는 역할을 제거해 추후 ViewContoller에서 처리할 수 있도록 했습니다
그랬더니 코드도 훨씬 깔끔해지고, 추후 ViewController에서 서브 스레드에서 처리할 일과 메인 스레드에서 처리할 일을
나누어 핸들러를 넣어줄 수 있게되어 구조적으로 더 좋아진 것 같습니다
추가적으로 class일 이유가 없다고 생각하여 struct로 바꾸었습니다 
HTTPManager도 struct로 바꾸는게 나았을텐데 깜빡했네요 이 부분은 Step2에서 변경하도록 하겠습니다

cc. @wonhee009

2022-01-26 10:16 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/Page.swift
> +struct Page<T: Decodable>: Decodable {
그렇다면 Page에 정의된 다른 프로퍼티들도 이전 프로젝트에서도 필요한 것들일까요?

2022-01-26 10:18 UTC, wonhee009 commented on OpenMarket/OpenMarket/Util/JSONCoder.swift
> +    }
Data decoding이 추후 커스텀될 필요가 있는 경우가 어떤 경우일까요?

2022-01-26 10:55 UTC, cms7371 commented on OpenMarket/OpenMarket/Util/JSONCoder.swift
> +    }
처음에는 날짜를 Date로 디코딩을 시도했다가 서버상의 날짜 표현 방식이
JSONDecoder에서 제공하는 기본 형식으로 디코딩 되지 않아서 우선 String으로 디코딩하도록 했습니다
추후 날짜를 이용할 생기면 JSONDecoder의 dateDecodingStrategy를 formatted나 custom으로
바꿀 필요가 있다고 생각했습니다

2022-01-26 11:02 UTC, cms7371 commented on OpenMarket/OpenMarket/Model/Page.swift
> +struct Page<T: Decodable>: Decodable {
학생 때 진행했던 프로젝트에서는 가져올 모델이 그렇게 많지 않아 한 번의 요청으로 
서버의 자원을 모두 받아올 수 있어 Page의 다른 프로퍼티를 이용하지는 않았었습니다.
하지만 이번 마켓 프로젝트에서는 서버 상의 Product가 많기 때문에 Product를 일부분씩 가져와야 한다고 생각했습니다.
이때 has_next 프로퍼티를 이용해서 다음 Page의 존재 여부를 확인하며 요청을 보낼 수 있을 것 같습니다!

다른 프로퍼티의 경우 활용할 일이 잘 없을 것 같아 만일 불필요한 프로퍼티를 디코딩하는 것이
바람직하지 않다면 없애는 것이 적절할 것 같습니다

2022-01-27 02:56 UTC, wonhee009 commented on OpenMarket/OpenMarket/Model/Page.swift
> +struct Page<T: Decodable>: Decodable {
> Page가 Product만을 items로 갖는 것이 아닌 더 포괄적인 개념이라 생각해 제네릭으로 하는 것이 맞다고 판단

위에 적어주신 코멘트를 오픈 마켓 프로젝트 내에서 다른 API 응답이 Page 형태로 내려온다면 해당 model을 사용하기 위해 제네릭을 선언했다고 이해했는데요.
그렇다면 다른 API 응답으로 
```swift
Pages {
  A: “aa”
  Items: [
    ...
  ]
}
```
이렇게 내려온다면 현재 정의해둔 model을 사용할 수 있을까요?

2022-01-27 03:19 UTC, wonhee009 commented on OpenMarket/OpenMarket/Util/JSONCoder.swift
> +    }
`JSONCoder`라는 이름만 봤을때에는 해당 class는 디코딩/인코딩의 역할만 있는거 같습니다.
또한, `JSONCoder`라고 네이밍한 이유는 디코딩/인코딩을 범용적으로 사용하기 위해서라고 이해했는데요.
DateDecodingStrategy를 설정하는게 범용적인가?라는 생각이 드네요.🧐

2022-01-27 05:04 UTC, cms7371 commented on OpenMarket/OpenMarket/Model/Page.swift
> +struct Page<T: Decodable>: Decodable {
A라는 프로퍼티가 있는 것에서 현재 모델은 사용할 수 없을 것 같습니다

하지만 나중에 유저 검색 기능이 생겨서 유저들을 get하는 API가 생기게 되면은 그때는
Page<User>의  형태로 변경 없이 이용될 수 있을 것이라 생각했습니다

2022-01-27 05:07 UTC, cms7371 commented on OpenMarket/OpenMarket/Util/JSONCoder.swift
> +    }
물론 DateDecodingStrategy 없이 Date로 디코딩할 수 있는 형태로 서버에서 내려온다면 좋겠지만
현재의 경우 JSONDecoder에서 바로 디코딩 할 수 없는 형태로 주어져 Strategy를 적용하는 것이 범용적이진 않더라도
현재 프로젝트 내에서는 한 번 정의해서 공통되게 사용할 수 있다는 장점이 있다고 생각합니다.

2022-01-28 13:06 UTC, wonhee009 approved these changes
JSONCoder, Generic은 따로 채팅으로 얘기해봤습니다.
이후 스텝에 반영하기로 해서 merge합니다:)
다음 스텝도 화이팅ᕕ( ᐛ )ᕗ!

2022-01-28 13:06 UTC, merged