오픈마켓 [STEP 1] liam
yagom-academy/ios-open-market-new pull request #8
Opened 2022-01-25 10:27 UTC by liam-777

@zdodev 

소대 안녕하세요! 이번 오픈마켓 프로젝트 리뷰를 부탁 드리게 될 리암입니다 ..!
잘 부탁드립니다 👍

# 구현 내용 및 고민한 점

* 엔티티 타입 :  네트워크로 부터 받아오는 JSON을 직접 디코딩하게 될  `GetOpenMarketProductListResponse` 타입과 `GetDetailOpenMarketProductResponse` 타입을 Decodable로 구현하였습니다.

* 모델 타입 : 그리고 앱 내에서 사용할 모델인 `OpenMarketProduct` 와  `Vendor` 를 따로 정의했습니다. 

🤔 현재 `OpenMarketAPIManager` 메서드의 핸들러에서 엔티티 값을 처리할 수 있도록 해 두었습니다. 이후에 ViewModel 계층에서 (또는 계층을 더 나누어서) 우리가 사용하는 모델 타입으로 변환해주고자 하는데 이런 방식이 괜찮을까요?

* OpenMarketAPIManager 내에 urlSession 프로퍼티를 두어서 이를 생성자에서 주입받도록 하였습니다. 이후에 테스트 코드에서 "네트워크 상황과 무관한 네트워킹 데이터 타입의 단위 테스트"를 구현해보고자 했는데 아직 학습이 더 필요할 것 같습니다 🥲 

* 현재 GET 메서드 두 개만 구현한 상태안데, 공통으로 뺄 수 있는 부분은 메서드 또는 `OpenMarketAPIRouter` 에서 구현하고자 했습니다. 
  * 라우터에서는 api마다 query, path, header, method 타입까지 정의된 URLRequest를 `asURLRequest` 메서드를 통해 생성하도록 하였습니다.  

🤔 네트워킹 과정 중 에러 처리를 진행하고 있습니다. 저는 statusCode 별 에러까지 따로 정의해줘서 확인시켜주고 있는데 이렇게 하는 것이 일반적이지는 않은 것 같습니다 .. 보통은 어떤 기준으로 Error를 커스텀하는 것이 일반적인지 궁굼합니다 !

2022-01-25 14:19 UTC, zdodev requested changes
안녕하세요. @liam-777 !
오픈마켓 스텝1 PR 축하합니다!🎉

네트워크 및 모델 타입 정의를 잘 해주셨습니다.👍

몇 가지 궁금점을 남겨보았습니다! 궁금하신 점 의견 나눠보면 좋을 것 같습니다.😁

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/ModelTests/ModelTests.swift
> +        wait(for: [expectation], timeout: 1)
비동기 단위 테스트를 작성해보셨네요. 좋습니다.👍

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/ModelTests/ModelTests.swift
> +    func test_getOpenMarketProductDetail_success인경우() {
다음 테스트가 실패하고 있어요!👀

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/APIConstants.swift
> +struct APIConstants {
HTTP 통신에 필요한 문자열을 `enum`들로 구현해보셨네요. 좋습니다.👍

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/APIConstants.swift
> +    static let baseURL = "https://market-training.yagom-academy.kr/api/products"
baseURL`의 범위를 `https://market-training.yagom-academy.kr/api/products` 까지 지정하신 이유가 궁금합니다.🤔
`host`와 `path` 범위를 한번 고민해보면 좋을 것 같습니다.😁

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIError.swift
> +enum OpenMarketAPIError: LocalizedError {
러를 상세하게 나눠보셨네요. 좋습니다.👍
에러를 상세하게 구분할수록, 에러에 대한 디테일한 컨트롤(에러 상태 표시 등)를 수행할 수 있어 장점이 될 수 있다고 생각합니다.
이 부분은 개인 또는 팀마다 여러 케이스로 나눠지지 않을까 생각합니다!😁

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIManager.swift
> +    }
`URLSession`을 주입받도록 구현해보셨네요. 좋습니다.👍

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIManager.swift
> +    func getOpenMarketProductList(pageNumber: Int, itemsPerPage: Int, completion: @escaping (Result<GetOpenMarketProudctListResponse, Error>) -> Void) {
`Result` 타입을 활용해보셨네요. 좋아요.👍
이런식으로 사용하고자 하는 타입으로 변환(or 디코딩)하는 방식도 좋습니다.👍

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIManager.swift
> +    private func handleOpenMarketAPIGetResponse<T: Decodable>(responseType: T.Type, response: URLResponse?, data: Data?) -> Result<T, Error> {
공통 기능을 메서드로 잘 구현해보신 것 같습니다.
에러를 상세하게 나누신 점도 좋습니다.👍

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIRespone.swift
> +struct GetOpenMarketProudctListResponse: Decodable, Equatable {
타입 이름을 `Get`으로 시작하도록 작성하신 특별한 이유가 있을까요?🤔

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIRespone.swift
> +struct GetDetailOpenMarketProductResponse: Decodable, Equatable {
타입 이름을 `Get`으로 시작하도록 작성하신 특별한 이유가 있을까요?🤔
`GetOpenMarketProudctListResponse` 타입과 다른 파일에서 관리해보는 것은 어떨까요?🤔

2022-01-25 14:19 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIRouter.swift
> +enum OpenMarketAPIRouter {
좋습니다.👏

2022-01-25 14:25 UTC, liam-777 commented on OpenMarket/ModelTests/ModelTests.swift
> +    func test_getOpenMarketProductDetail_success인경우() {
제대로 비교가 되는지 확인해보려고 데이터를 살짝 바꿨었는데 다시 수정한다는걸 깜빡했네요 😅

2022-01-25 14:25 UTC, liam-777 commented on OpenMarket/OpenMarket/OpenMarketAPI/APIConstants.swift
> +    static let baseURL = "https://market-training.yagom-academy.kr/api/products"
이번 프로젝트에 사용하게 될 모든 endpoint가 prdoucts인 것 같아서 포함시켰었는데 분리시키겠습니다! 감사합니다 👍

2022-01-25 14:28 UTC, liam-777 commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketAPIRespone.swift
> +struct GetOpenMarketProudctListResponse: Decodable, Equatable {
HTTP GET 메서드인 OpenMarketProductList API (상품 리스트 조회)의 response라는 뜻에서 지었습니다.
소대가 보시기에 햇갈린 네이밍이였으면 수정하는게 맞을 것 같네요 ..! 반영하겠습니다.

2022-01-26 11:29 UTC, zdodev approved these changes
안녕하세요. @liam-777 !

스텝1 진행하시느라 고생하셨습니다. 이번 스텝은 여기서 마무리 하도록 하겠습니다.
약간의 코멘트를 남겨보았습니다. 다음 스텝도 화이팅입니다!👍

2022-01-26 11:29 UTC, zdodev commented on OpenMarket/OpenMarket/OpenMarketAPI/OpenMarketProductDetailGetResponse.swift
> +struct OpenMarketProductDetailGetResponse: Decodable, Equatable {
`OpenMarketProudctListGetResponse` 과 함께 폴더로 관리해도 좋을 것 같습니다!

2022-01-26 11:29 UTC, zdodev commented on OpenMarket/ModelTests/ModelTests.swift
> +        )
`expectedResponse` 을 정의하는 코드 길이가 길어보입니다. 해당 부분은 다른 곳에서 생성해서 주입해도 좋을 것 같습니다!

2022-01-26 11:29 UTC, merged